# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VJF-MITDT
version:      1.0
version_from: lib/VJF/MITDT.pm
installdirs:  site
requires:
    Getopt::Lucid:                 0.16
    VJF::Emphase:                  0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
